config/routes.rb
Rails.application.routes.draw do
  scope ":locale", locale: /en|pt/ do
    resources :rooms do
      resources :reviews, only: [:create, :update], module: :rooms
    end
    resources :users
  end

  resource :confirmation, only: [:show]
  resource :user_sessions, only: [:create, :new, :destroy]

  get '/:locale' => 'home#index', locale: /en|pt/
  root 'home#index'
end

app/models/review.rb
class Review < ActiveRecord::Base
  POINTS = (1..5).to_a

  belongs_to :user
  belongs_to :room, counter_cache: true

  validates_uniqueness_of :user_id, scope: :room_id
  validates_presence_of :points, :user_id, :room_id
  validates_inclusion_of :points, in: POINTS

  def self.stars
    (average(:points) || 0).round
  end
end

app/models/room.rb
class Room < ActiveRecord::Base
  extend FriendlyId

  has_many :reviews, dependent: :destroy
  belongs_to :user

  validates_presence_of :title
  validates_presence_of :slug

  mount_uploader :picture, PictureUploader
  friendly_id :title, use: [:slugged, :history]

  scope :most_recent, -> { order(created_at: :desc) }

  def complete_name
    "#{title}, #{location}"
  end

  def self.search(query)
    if query.present?
      where(['location ILIKE :query OR
              title ILIKE :query OR
              description ILIKE :query', query: "%#{query}%"])
    else
      all
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  EMAIL_REGEXP = /\A[^@]+@([^@\.]+\.)+[^@\.]+\z/

  has_many :rooms, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :reviewed_rooms, through: :reviews, source: :room

  scope :confirmed, -> { where.not(confirmed_at: nil) }

  validates_presence_of :email, :full_name, :location, :bio
  validates_length_of :bio, minimum: 30, allow_blank: false
  validates_uniqueness_of :email

  validate :email_format

  has_secure_password

  before_create do |user|
    user.confirmation_token = SecureRandom.urlsafe_base64
  end

  def self.authenticate(email, password)
    confirmed.
      find_by(email: email).
      try(:authenticate, password)
  end

  def confirm!
    return if confirmed?

    self.confirmed_at = Time.current
    self.confirmation_token = ''
    save!
  end

  def confirmed?
    confirmed_at.present?
  end

  private
    def email_format
      errors.add :email, :invalid unless email.match(EMAIL_REGEXP)
    end
end

app/models/user_session.rb
class UserSession
  include ActiveModel::Model

  attr_accessor :email, :password
  validates_presence_of :email, :password

  def initialize(session, attributes={})
    @session = session
    @email = attributes[:email]
    @password = attributes[:password]
  end

  def authenticate!
    user = User.authenticate(@email, @password)

    if user.present?
      store(user)
    else
      errors.add(:base, :invalid_login)
      false
    end
  end

  def store(user)
    @session[:user_id] = user.id
  end

  def current_user
    User.find(@session[:user_id])
  end

  def user_signed_in?
    @session[:user_id].present?
  end

  def destroy
    @session[:user_id] = nil
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  delegate :current_user, :user_signed_in?, to: :user_session
  helper_method :current_user, :user_signed_in?

  before_action do
    I18n.locale = params[:locale]
  end

  def default_url_options
    { locale: I18n.locale }
  end

  def user_session
    UserSession.new(session)
  end

  def require_authentication
    unless user_signed_in?
      redirect_to new_user_sessions_path,
        alert: t('flash.alert.needs_login')
    end
  end

  def require_no_authentication
    if user_signed_in?
      redirect_to root_path,
        alert: t('flash.notice.aleready_loggged_in')
    end
  end
end

app/controllers/confirmations_controller.rb
class ConfirmationsController < ApplicationController
  def show
    user = User.find_by(confirmation_token: params[:token])

    if user.present?
      user.confirm!
      redirect_to user,
        notice: I18n.t('confirmations.success')
    else
      redirect_to root_path
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @rooms = Room.take(3)
  end
end

app/controllers/rooms/reviews_controller.rb
class Rooms::ReviewsController < ApplicationController
  before_filter :require_authentication

  def create
    review = room.reviews.
      find_or_initialize_by(user_id: current_user.id)

    review.update!(review_params)

    head :ok
  end

  def update
    create
  end

  private

  def room
    @room ||= Room.find(params[:room_id])
  end

  def review_params
    params.
      require(:review).permit(:points)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  PER_PAGE = 10

  before_action :set_room, only: [:show]
  before_action :set_users_room, only: [:edit, :update, :destroy]
  before_action :require_authentication,
    only: [:new, :edit, :create, :update, :destroy]

  def index
    @search_query = params[:q]

    rooms = Room.search(@search_query).
      most_recent.
      page(params[:page]).
      per(PER_PAGE)

    @rooms = RoomCollectionPresenter.new(rooms, self)
  end

  def show
    if user_signed_in?
      @user_review = @room.reviews.
        find_or_initialize_by(user_id: current_user.id)
    end
  end

  def new
    @room = current_user.rooms.build
  end

  def edit
  end

  def create
    @room = current_user.rooms.build(room_params)

    if @room.save
      redirect_to @room, notice: t('flash.notice.room_created')
    else
      render :new
    end
  end

  def update
    if @room.update(room_params)
      redirect_to @room, notice: t('flash.notice.room_updated')
    else
      render :edit
    end
  end

  def destroy
    @room.destroy
    redirect_to rooms_url
  end

  private

  def set_room
    room_model = Room.friendly.find(params[:id])
    @room = RoomPresenter.new(room_model, self)
  end

  def set_users_room
    @room = current_user.rooms.friendly.find(params[:id])
  end

  def room_params
    params.require(:room).permit(:title, :location, :description, :picture)
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  before_action :require_no_authentication, only: [:new, :create]
  before_action :require_authentication, only: :destroy
  
  def new
    @user_session = UserSession.new(session)
  end

  def create
    @user_session = UserSession.new(session, params[:user_session])

    if @user_session.authenticate!
      redirect_to root_path, notice: t('flash.notice.signed_in')
    else
      render :new
    end
  end

  def destroy
    user_session.destroy
    redirect_to root_path, notice: t('flash.notice.signed_out')
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_no_authentication, only: [:new, :create]
  before_action :can_change, only: [:edit, :update]
  
  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      Signup.confirm_email(@user).deliver

      redirect_to @user, notice: 'Cadastro criado com sucesso!'
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to @user, notice: 'Cadastro atualizado com sucesso!'
    else
      render :edit
    end
  end

  private

  def user_params
    params
      .require(:user)
      .permit(
        :email,
        :full_name,
        :location,
        :password,
        :password_confirmation,
        :bio
      )
  end

  def can_change
    unless user_signed_in? && current_user == user
      redirect_to user_path(params[:id])
    end
  end

  def user
    @user ||= User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def error_tag(model, attribute)
    if model.errors.has_key? attribute
      content_tag(
        :div,
        model.errors[attribute].first,
        class: 'error_message'
      )
    end
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
  def belongs_to_user(room)
    user_signed_in? && room.user == current_user
  end
end

app/views/home/index.html.erb
<h1>Quartos recém postados</h1>

<uL>
  <% @rooms.each do |room| %>
    <li>
      <%= link_to room.complete_name, room %>
    </li>
  <% end %>
</uL>

app/views/layouts/_user_navbar.html.erb
<nav>
  <ul>
    <li><%= link_to t('layout.new_room'), new_room_path %></li>
    <li><%= link_to t('layout.rooms'), rooms_path %></li>
    <li>
      <%= link_to t('layout.my_profile'), user_path(current_user) %>
    </li>
    <li>
      <%= link_to t('layout.signout'), user_sessions_path, method: :delete %>
    </li>
  </ul>
</nav>

app/views/layouts/_visitor_navbar.html.erb
<nav>
  <ul>
    <li><%= link_to t('layout.rooms'), rooms_path %></li>
    <li><%= link_to t('layout.signup'), new_user_path %></li>
    <li><%= link_to t('layout.signin'), new_user_sessions_path %></li>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ColchoNet</title>
    <link href='http://fonts.googleapis.com/css?family=Pacifico' rel='stylesheet' type='text/css' />
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <div class="header-wrap">
        <h1><%= link_to "colcho.net", root_path %></h1>
        <% if user_signed_in? %>
          <%= render 'layouts/user_navbar' %>
        <% else %>
          <%= render 'layouts/visitor_navbar' %>
        <% end %>        
      </div>
    </header>

    <div id="content">
      <% if notice.present? %>
        <p id="notice"><%= notice %></p>
      <% end %>
      <% if alert.present? %>
        <p id="alert"><%= alert %></p>
      <% end %>
      <%= yield %>
    </div>

  </body>
</html>

app/views/rooms/_form.html.erb
<%= form_for(@room) do |f| %>
  <% if @room.errors.any? %>
    <div id='error_explanation'>
      <%= t 'general.form_error' %>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
    <%= error_tag @room, :title %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
    <%= error_tag @room, :location %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
    <%= error_tag @room, :description %>
  </div>
  <div>
    <%= f.label :picture %><br>
    <%= f.file_field :picture %>
    <%= error_tag @room, :picture %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rooms/_review.html.erb
<section class="review">
  <% if room.show_form? %>
    <%= render partial: 'review_form', locals: {room: room} %>
  <% else %>
    <% room.stars.times do %>
      <%= fa_icon 'star' %>
    <% end %>

    <% (room.review_points.max - room.stars).times do %>
      <%= fa_icon 'star-o' %>
    <% end %>

    <%= t '.stats', count: room.total_reviews %>
  <% end %>
</section>

app/views/rooms/_review_form.html.erb
<% if room.can_review? %>
  <%= form_for room.review_route, remote: true do |f| %>
    <% room.review_points.each do |point| %>
      <%= f.radio_button :points, point  %>
      <%= f.label :points, value: point do %>
        <%= fa_icon 'star' %>
      <% end %>
    <% end %>

    <%= f.submit %>
  <% end %>
<% else %>
  <span class="login_required">
    <%= t('.login_to_review') %>
  </span>
<% end %>

app/views/rooms/_room.html.erb
<article class='room'>
  <h2>
    <%= link_to highlight(room.title, @search_query), room.route %>
  </h2>

  <%= render partial: 'review', locals: {room: room} %>

  <div class="room_description">
    <%= link_to(
          image_tag(room.thumb_url),
          room.picture_url
        ) if room.has_picture? %>

     <p>
       <%= highlight(room.description || '', @search_query) %>
     </p>
  </div>

  <% if belongs_to_user(room) %>
    <ul>
      <li><%= link_to t('.edit'), edit_room_path(room.route) %></li>
      <li><%= link_to t('.destroy'), room_path(room.route),
            method: :delete,
            data: {confirm: t('dialogs.destroy')} %>
      </li>
    </ul>
  <% end %>
</article>

app/views/rooms/_search.html.erb
<%= form_tag rooms_path, method: :get, class: 'search' do %>
  <%= text_field_tag :q, @search_query, placeholder: t('.search_for') %>
<% end %>

app/views/rooms/edit.html.erb
<h1><%= t '.title' %></h1>
<%= render 'form' %>
<%= link_to 'Show', @room %> |
<%= link_to t('links.back'), rooms_path %>

app/views/rooms/index.html.erb
<%= render 'search' %>

<h1>
  <% if @search_query.present? %>
    <%= t '.search_results' %>
  <% else %>
    <%= t '.title' %>
  <% end %>
</h1>

<%= render @rooms %>

<%= paginate @rooms %>

app/views/rooms/new.html.erb
<h1><%= t '.title' %></h1>
<%= render 'form' %>
<%= link_to t('links.back'), rooms_path %>

app/views/rooms/show.html.erb
<%= render @room %>

app/views/signup/confirm_email.html.erb
<h1><%= t '.title' %></h1>
<p>
  <%= t '.body', full_name: @user.full_name %>
</p>
<p>
  <%= t '.confirm_link_html', link: link_to(@confirmation_link, @confirmation_link) %>
</p>
<p>
  <%#= t '.thanks_html', link_to('Colcho.net', root_url) %>
  <%= t '.thanks_html', link: root_url %>
</p>

app/views/signup/confirm_email.text.erb
<%= t '.title' %>

<%= t '.body', full_name: @user.full_name %>

<%= t '.confirm_link_html', link: @confirmation_link %>

<%= t '.thanks_html', link: root_url %>

app/views/user_sessions/new.html.erb
<h1><%= t '.title' %></h1>

<% if @user_session.errors.has_key? :base %>
  <div id='error_explanation'>
    <%= @user_session.errors[:base].join(', ') %>
  </div>
<% end %>

<%= form_for @user_session do |f| %>
  <p>
    <%= f.label :email %>
    <%= f.text_field :email %>
    <%= error_tag @user_session, :email %>
  </p>
  <p>
    <%= f.label :password %>
    <%= f.text_field :password %>
    <%= error_tag @user_session, :password %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

<P><%= link_to t('.sign_up'), new_user_path %></P>

app/views/users/edit.html.erb
<h1><%= t '.title' %></h1>
<%= render 'users/partials/form' %>
<%= link_to t('links.back'), @user %>

app/views/users/new.html.erb
<h1><%= t '.title' %></h1>
<%= render 'users/partials/form' %>
<%= link_to t('links.back'), root_path %>

app/views/users/partials/_form.html.erb
<% if @user.errors.any? %>
  <div id='error_explanation'>
    <%= t 'general.form_error' %>
  </div>
<% end %>

<%= form_for @user do |f| %>
  <p>
    <%= f.label :full_name %><br />
    <%= f.text_field :full_name %>
    <%= error_tag @user, :full_name %>
  </p>
  <p>
    <%= f.label :location %><br />
    <%= f.text_field :location %>
    <%= error_tag @user, :location %>
  </p>
  <p>
    <%= f.label :email %><br />
    <%= f.text_field :email %>
    <%= error_tag @user, :email %>
  </p>
  <p>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
    <%= error_tag @user, :password %>
  </p>
  <p>
    <%= f.label :password_confimartion %><br />
    <%= f.password_field :password_confimartion %>
    <%= error_tag @user, :password_confimartion %>
  </p>
  <p>
    <%= f.label :bio %><br />
    <%= f.text_area :bio %>
    <%= error_tag @user, :bio %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/users/show.html.erb
<h1><%= t '.title', user_name: @user.full_name %></h1>

<ul>
  <li><%= t '.location', location: @user.location %></li>
  <li><%= t '.bio', bio: @user.bio %></li>
  </li>
</ul>

<%= link_to t('.edit'), edit_user_path(@user) %>
<%= link_to 'Home', root_path %>